export interface ComplianceClause { framework: string; clause_id: string; clause_text: string; }
export interface AIOpinion { impact: "SYSTEM-WIDE" | "HIGH" | "LOCAL"; likelihood: string; priority: "CRITICAL" | "HIGH" | "MEDIUM"; reason: string; }
export interface Finding { rule_id: string; severity: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW"; mitre_id: string; cvss: number; affected_nodes: string[]; description: string; remediation: string; plugin: "zero_trust" | "quantum" | "attack_path" | "supply_chain"; compliance_clauses: ComplianceClause[]; business_impact: string; business_risk: string; ai_opinion: AIOpinion; qvi?: number; risk_year?: number; cve_id?: string; fix_version?: string; path_risk?: number; mitre_name?: string; mitre_tactic?: string; mapping_basis?: string; entry_type?: string; target_type?: string; }
export interface GraphNode { id: string; name?: string; type: string; zone: "PUBLIC" | "DMZ" | "INTERNAL" | "PRIVATE" | "RESTRICTED"; data_sensitivity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL"; encryption_type: string; blast_radius: number; cvss_live: number; cve_id?: string; known_exploit?: boolean; retention_years?: number; }
export interface GraphEdge { source: string; target: string; auth_required: boolean; mfa_required: boolean; tls_enforced: boolean; access_scope: "FULL" | "SCOPED" | "READ_ONLY"; }
export interface GraphJson { nodes: GraphNode[]; edges: GraphEdge[]; }
export interface ConfidenceWarning { edge: string; downgraded_claims: string[]; reason: string; implication: string; evidence_source: string; confidence: number; }
export interface ScoreBreakdown { zero_trust: number; quantum: number; attack_path: number; supply_chain: number; compliance: number; total: number; per_finding_deltas?: Record<string, number>; }
export interface Patch { title: string; score_impact: string; difficulty: "easy" | "medium" | "hard"; affected_node: string; rule_id: string; severity: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW"; notes?: string; terraform?: { file: string; instructions: string; content: string }; iam?: { file: string; instructions: string; content: string }; kubernetes?: { file: string; instructions: string; content: string }; }
export interface ExecutiveSummary { security_index: number; risk_level: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW"; critical_count: number; high_count: number; attack_paths: number; main_risk: string; primary_action: string; score_breakdown: ScoreBreakdown; attack_stories: string[]; }
export interface EngineStatus { zt: "ok" | "failed"; quantum: "ok" | "failed"; ap: "ok" | "failed"; sc: "ok" | "failed"; }
export interface ScanResult { id: string; org_id: string; name: string; status: "pending" | "running" | "complete" | "failed"; security_index: number; node_count: number; duration_ms: number; created_at: string; completed_at?: string; evidence_source: string; graph_json: GraphJson; score_breakdown: ScoreBreakdown; risk_summary: { CRITICAL: number; HIGH: number; MEDIUM: number; LOW: number }; findings: Finding[]; executive_summary: ExecutiveSummary; confidence_warnings: ConfidenceWarning[]; auto_fix_patches: Patch[]; engine_status: EngineStatus; }
export interface ScanStatus { status: "pending" | "running" | "complete" | "failed"; security_index?: number; engine_status?: EngineStatus; duration_ms?: number; }
